Repository Ditmar/OpenScience, pull requests merged in 2025-06, with the labels that each got.

#413 feat: update design tokens for improved styling and typography consis…
  src/style-library/themes/tokens/tokens.json
  src/style-library/themes/tokens/tokens.ts
Labels: Refactor

#375 Refactor_CountryListDropdown
  src/ui/components/atoms/CountryFlag/CountryFlag.tsx
  src/ui/components/atoms/CountryText/CountryText.tsx
  src/ui/components/atoms/DropdownButton/DropdownButton.tsx
  src/ui/components/molecules/CountrySelectList/CountrySelectList.tsx
  src/ui/components/organisms/CountryListDropdown/CountryListDropdown.stories.tsx
  src/ui/components/organisms/CountryListDropdown/CountryListDropdown.test.tsx
  src/ui/components/organisms/CountryListDropdown/CountryListDropdown.tsx
  src/ui/components/organisms/CountryListDropdown/MockCountries.ts
  src/ui/components/organisms/CountryListDropdown/types/IProps.ts
Labels: needs works

#412 feat: add branch name sanitization step in GitHub Actions workflow an…
  .github/workflows/publish.yml
Labels: needs works

#406 feat: use matrial UI media queries
  docs/breakpoints.md
  src/layouts/screen-size-rules/breakpoints.ts
  src/layouts/screen-size-rules/media-queries.stories.tsx
  src/layouts/screen-size-rules/media-queries.ts
  src/layouts/screen-size-rules/theme.ts
  src/layouts/screen-size-rules/typography-responsive.ts
Labels: needs works

#294 Text card stat
  src/ui/components/molecules/text-card-stat/TextCardStat.module.scss
  src/ui/components/molecules/text-card-stat/TextCardStat.stories.tsx
  src/ui/components/molecules/text-card-stat/TextCardStat.test.tsx
  src/ui/components/molecules/text-card-stat/TextCardStat.tsx
  src/ui/components/molecules/text-card-stat/types/IProps.ts
Labels: review soon, needs works

#377 Configuración de configManager para manejo de variables de entorno - feature/CORE-352
  .eslintrc.cjs
  README.md
  app-server/server.mjs
  config-manager/config-manager.ts
  docs/Config-manager.md
  package.json
  src/config/__tests__/config-manager.test.ts
  src/middleware/config-middleware.ts
  src/pages/index.astro
  src/types/locals.d.ts
  yarn.lock
Labels: needs works, core

#386 Feature/FRONTEND-345 Refactor Implementar componente Default Input
  src/ui/components/atoms/Atoms-DefaultInputs/ClearIcon.tsx
  src/ui/components/atoms/Atoms-DefaultInputs/EmailIcon.tsx
  src/ui/components/atoms/Atoms-DefaultInputs/HintText.tsx
  src/ui/components/atoms/Atoms-DefaultInputs/InfoIcon.tsx
  src/ui/components/atoms/Atoms-DefaultInputs/TextInput.tsx
  src/ui/components/molecules/DefaultInputs/DefaultInput.test.tsx
  src/ui/components/molecules/DefaultInputs/DefaultInput.tsx
  src/ui/components/molecules/DefaultInputs/DefaultInputs.stories.tsx
  src/ui/components/molecules/DefaultInputs/HookDefaultInput.ts
  src/ui/components/molecules/DefaultInputs/types/types.ts
Labels: needs works
