Repository Ditmar/OpenScience, pull requests merged in 2025-05, with the labels that each got.

#288 Feature/frontend 278
  docs/style-library.md
  package-lock.json
  package.json
  scripts/tokenizer.mjs
  src/middleware/loadEmotionCache.ts
  src/style-library/core/MuiApp.tsx
  src/style-library/core/ThemeSwitcher.tsx
  src/style-library/createEmotionCache.ts
  src/style-library/providers/ThemeProvider.tsx
  src/style-library/providers/useThemeProvider.ts
  src/style-library/stories/Alert.stories.tsx
  src/style-library/stories/Avatar.stories.tsx
  src/style-library/stories/Button.stories.tsx
  src/style-library/stories/Typography.stories.tsx
  src/style-library/themes/dark.ts
  src/style-library/themes/default.ts
  src/style-library/themes/tokens/tokens.json
  src/style-library/themes/tokens/tokens.ts
  style-guide/rules/base.js
  yarn.lock
Labels: Atomic Design

#314 Feature/frontend 259
  .storybook/main.ts
  .vscode/settings.json
  astro.config.mjs
  docs/svg-icons-integration.md
  package.json
  src/env.d.ts
  src/pages/index.astro
  src/ui/components/atoms/icon-svgr/SvgIcons.stories.tsx
  src/ui/utils/hooks/useDynamicIcon.tsx
  src/ui/utils/vite-svgr/Icon.tsx
  src/ui/utils/vite-svgr/Loader.tsx
  src/ui/utils/vite-svgr/loadSvgIcon.ts
  src/ui/utils/vite-svgr/types/IProps.ts
  src/ui/utils/vite-svgr/types/IconType.ts
  yarn.lock
Labels: bug

#300 add tooltips
  src/ui/components/molecules/InfoTooltip/InfoTooltip.module.scss
  src/ui/components/molecules/InfoTooltip/InfoTooltip.stories.tsx
  src/ui/components/molecules/InfoTooltip/InfoTooltip.test.tsx
  src/ui/components/molecules/InfoTooltip/InfoTooltip.tsx
  src/ui/components/molecules/InfoTooltip/TooltipIcon.tsx
  src/ui/components/molecules/InfoTooltip/types/IProps.ts
Labels: needs works

#291 feat: add IconTextStat component with styles and tests
  src/globals/_variables.scss
  src/library/component/molecules/icon-text-stat/icon-text-stat.module.scss
  src/library/component/molecules/icon-text-stat/icon-text-stat.stories.tsx
  src/library/component/molecules/icon-text-stat/icon-text-stat.test.tsx
  src/library/component/molecules/icon-text-stat/icon-text-stat.tsx
  src/library/component/molecules/icon-text-stat/types/IProps.ts
  src/library/component/molecules/icon-text-stat/types/iconMap.ts
Labels: needs works

#280 feat: add OLItem component with styles and tests
  src/globals/_variables.scss
  src/ui/components/atoms/ol-item/OLItem.module.scss
  src/ui/components/atoms/ol-item/OLItem.stories.tsx
  src/ui/components/atoms/ol-item/OLItem.test.tsx
  src/ui/components/atoms/ol-item/OLItem.tsx
  src/ui/components/atoms/ol-item/types/IProps.ts
Labels: rebase soon

#317 feature/FRONTED-270
  src/ui/components/atoms/CountryList/CountryList.module.scss
  src/ui/components/atoms/CountryList/CountryList.stories.tsx
  src/ui/components/atoms/CountryList/CountryList.test.tsx
  src/ui/components/atoms/CountryList/CountryList.tsx
  src/ui/components/atoms/CountryList/__snapshots__/CountryList.test.tsx.snap
Labels: needs works

#287 feat: Refactor SCSS add Grid Componenet
  src/globals/_breakpoints.scss
  src/globals/_variables.scss
  src/layouts/gridly/breakpoints-grid.scss
  src/layouts/gridly/gridzone.scss
  src/stories/GridSystem.stories.tsx
Labels: rebase soon

#313 feat: add Heading component with typography styles and tests
  .vscode/settings.json
  src/env.d.ts
  src/globals/_fonts.scss
  src/globals/_typography.scss
  src/library/component/atoms/pills/pills.module.scss
  src/ui/components/atoms/HeadingTitle/HeadingTitle.module.scss
  src/ui/components/atoms/HeadingTitle/HeadingTitle.stories.tsx
  src/ui/components/atoms/HeadingTitle/HeadingTitle.test.tsx
  src/ui/components/atoms/HeadingTitle/HeadingTitle.tsx
  src/ui/components/atoms/HeadingTitle/types/IProps.ts
  src/ui/components/atoms/ol-bullet/OLBullet.module.scss
  yarn.lock
Labels: needs works

#310 feat: implement UserTextCard component with tests and stories
  src/library/component/molecules/user-text-card/types/IProps.ts
  src/library/component/molecules/user-text-card/user-text-card.module.scss
  src/library/component/molecules/user-text-card/user-text-card.stories.tsx
  src/library/component/molecules/user-text-card/user-text-card.test.tsx
  src/library/component/molecules/user-text-card/user-text-card.tsx
Labels: needs works

#312 feat: implement PhoneDropdown component with flags, dial codes, sizes, and states
  src/library/component/molecules/phone-dropdown/PhoneDropdown.module.scss
  src/library/component/molecules/phone-dropdown/PhoneDropdown.stories.tsx
  src/library/component/molecules/phone-dropdown/PhoneDropdown.test.tsx
  src/library/component/molecules/phone-dropdown/PhoneDropdown.tsx
  src/library/component/molecules/phone-dropdown/types/IProps.ts
Labels: needs works

#322 feature(common): add component badges[FRONTEND-249]
  .vscode/settings.json
  src/env.d.ts
  src/globals/_breakpoints.scss
  src/globals/_fonts.scss
  src/globals/_typography.scss
  src/globals/_variables.scss
  src/layouts/gridly/breakpoints-grid.scss
  src/layouts/gridly/gridzone.scss
  src/library/component/atoms/pills/pills.module.scss
  src/library/component/molecules/icon-text-stat/icon-text-stat.module.scss
  src/library/component/molecules/phone-dropdown/PhoneDropdown.module.scss
  src/stories/GridSystem.stories.tsx
  src/ui/components/atoms/CountryList/CountryList.module.scss
  src/ui/components/atoms/HeadingTitle/HeadingTitle.module.scss
  src/ui/components/atoms/badges/Icon.tsx
  src/ui/components/atoms/badges/badge.scss
  src/ui/components/atoms/badges/badge.stories.tsx
  src/ui/components/atoms/badges/badge.test.jsx
  src/ui/components/atoms/badges/badge.tsx
  src/ui/components/atoms/badges/types/IProps.ts
  src/ui/components/atoms/ol-bullet/OLBullet.module.scss
  src/ui/components/atoms/phone-input/phoneinput.module.scss
  src/ui/components/molecules/InfoTooltip/InfoTooltip.module.scss
Labels: needs works

#285 feature/FRONTED-07
  src/globals/main.scss
  src/globals/tokens.scss
  src/styles/tokens/border-radius.scss
  src/ui/components/atoms/tokens/BorderRadiusTokens.stories.tsx
Labels: needs works

#350 [feature/FRONTEND-267] feat: add country input with stories and test
  public/images/flags/ar.svg
  public/images/flags/bo.svg
  public/images/flags/cl.svg
  public/images/flags/pe.svg
  src/assets/icons/caret_down.svg
  src/assets/icons/close_circle.svg
  src/assets/icons/globe.svg
  src/assets/icons/info.svg
  src/ui/components/atoms/input-country/InputCountry.module.scss
  src/ui/components/atoms/input-country/InputCountry.stories.tsx
  src/ui/components/atoms/input-country/InputCountry.test.tsx
  src/ui/components/atoms/input-country/InputCountry.tsx
  src/ui/components/atoms/input-country/__snapshots__/InputCountry.test.tsx.snap
  src/ui/components/atoms/input-country/types/IProps.ts
Labels: Atomic Components
